# Generated by Django 5.0.6 on 2024-07-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_hotel_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
